included:
  - Sources
  - Package.swift

excluded:
  - .build
  - Packages
  - dist

reporter: xcode

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last

identifier_name:
  min_length:
    warning: 1
    error: 1
  excluded:
    - id
    - os

line_length:
  warning: 120
  ignores_comments: true
  ignores_urls: true
